name: TeamCity Services Diff Check
permissions: read-all

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/teamcity-services-diff-check.yml'
      - 'mmv1/third_party/terraform/!.teamcity'
jobs:
  terraform-provider-google:
    uses: ./.github/workflows/build-downstream.yml
    with:
      repo: 'terraform-provider-google'

  teamcity-services-diff-check-ga:
    needs: terraform-provider-google
    runs-on: ubuntu-22.04
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact-terraform-provider-google
          path: artifacts

      - name: Unzip the artifacts and delete the zip
        run: |
          unzip artifacts/output.zip -d ./
          rm artifacts/output.zip

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: Cache Go modules and build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-test-terraform-provider-google-${{hashFiles('go.sum','google-*/transport/**','google-*/tpgresource/**','google-*/acctest/**','google-*/envvar/**','google-*/sweeper/**','google-*/verify/**') }}
          restore-keys: |
              ${{ runner.os }}-test-terraform-provider-google-${{ hashFiles('go.sum') }}
              ${{ runner.os }}-test-terraform-provider-google-

      - name: Build Provider
        run: |
          go build

      - name: Diff Check
        run: |
          cd .teamcity/components/inputs
          go run diff_check.go