name: TeamCity Services Weekly Diff Check
permissions: read-all

on:
  # Enable ad hoc checks
  workflow_dispatch:
  
  # Scheduled checks to catch edge cases
  schedule:
    # Every Monday and Tuesday morning
    - cron:  '0 4 * * 1-2'

jobs:
  teamcity-services-diff-check:
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: TeamCity Google Provider Generate
          uses: ./.github/actions/build-downstream
          with:
            repo: 'terraform-provider-google'
            token: '$GITHUB_TOKEN'
        - run: export GOOGLE_REPO_PATH=$OUTPUT_PATH
        - name: TeamCity Google Beta Provider Generate
          uses: ./.github/actions/build-downstream
          with:
            repo: 'terraform-provider-google-beta'
            token: '$GITHUB_TOKEN'
        - run: export GOOGLE_BETA_REPO_PATH=$OUTPUT_PATH
        - name: Check that new services have been added to the TeamCity configuration code
          run: |
              # Create lists of service packages in providers
              ls ${GOOGLE_REPO_PATH}/google/services > tools/teamcity-diff-check/services_ga.txt
              ls ${GOOGLE_BETA_REPO_PATH}/google-beta/services > tools/teamcity-diff-check/services_beta.txt
    
              # Run tool to compare service packages in the providers vs those listed in TeamCity config files
              cd tools/teamcity-diff-check
              go run main.go -service_file=services_ga
              go run main.go -service_file=services_beta
